export const Houses = [
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1eQOdu9juXvudhnfXpBGo7id6glot4-07",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies Beautiful 3 storey house with all the faciliies",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:1,
  },
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1RgMOTM8SxcyuPCvMwveWOEKfqDDrsMWE",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies ",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:2,
  },
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1okv1OGJJNsfb0_X3iqWgMoZwX06dVx9o",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies ",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:3,
  },
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1r99VDn_E1azQYQYB9Bf3nHkmYLoD4QzG",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies ",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:4,
  },
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1OQ6DEm8SEpgiN84Gy91t5bzw5G6BFZTU",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies ",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:5,
  },
  {
    imageUrl: "https://drive.google.com/thumbnail?id=1AVl4FIsOCWZ5iRi_nt2V7mJ5oFMilDMT",
    title: "3 storey house",
    description: "Beautiful 3 storey house with all the faciliies ",
    price: "$500",
    location: "Nagdhunga Pokhara -9",
    id:6,
  },
];
